// client/src/modules/common/modals/components/modal.jsx
const React = require('react'),
    Component = require('modules/lib/component'),
    AlertStore = require('modules/common/alerts/stores/alert_store'),
    ModalStore = require('modules/common/modals/stores/modal_store'),
    _ = require('underscore')

module.exports = class Modal extends Component {
    constructor(props) {
        super(props)
        this.state = {show: false, _zindex: ModalStore.getZIndex()}

        this.event(ModalStore, props.id + '.show', this.showModal.bind(this))
        this.event(ModalStore, props.id + '.hide', this.hideModal.bind(this))
        this.event(ModalStore, 'hide', this.hideModal.bind(this))
    }

    showModal (options) {
        // React can not manage the body tag directly
        // So lets "hack" it and make the body not
        // have scroll bars. Otherwise we have two sets of scroll bars
        document.body.style.overflow = 'hidden'

        this.setState({show: true, _zindex: ModalStore.getZIndex()}, function(){
            if(_.isFunction(this.props.onShow)){
                this.props.onShow(options)
            }
        })
    }

    hideModal (options) {
        // Add the scroll bars back in for the body
        document.body.style.overflow = 'auto'

        // Remove all alerts
        AlertStore.hide()

        if(this.state.show){
            this.setState({show: false, _zindex: ModalStore.getZIndex()}, () => {
                if(_.isFunction(this.props.onHide)){
                    this.props.onHide(options)
                }
            })
        }
        
    }

    render () {
        if(!this.state.show) return null

        // A css id can not use dots in the name
        // but we want to keep the event namespace the
        // same as all the other components which uses dots
        var id = this.props.id.replace(/\./g, '-')

        return (
            <div id={id} style={{zIndex: this.state._zindex}} class="modal" tabIndex="-1" role="dialog" aria-labelledby="modal_label" aria-hidden="true">
                <div class="blank">
                    <div class="blank large-12 columns">
                        <h1><div class="float-right"><a onClick={this.hideModal.bind(this)}>+</a></div>{this.props.title}</h1>
                        <div class="modal-body">
                            {this.props.children}
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}

// client/src/modules/common/modals/components/Modal.svelte
<script lang="ts">
  import { fade } from 'svelte/transition';
  import { modalStore } from '../stores/ModalStore'
  import { alertStore } from '../../alerts/stores/AlertStore'
  import { subscribe } from '../../../lib/helpers';

  export let onShow = (options?: Record<string, any>) => {}
  export let onHide = (options?: Record<string, any>) => {}
  export let id: string
  export let title: string = ''
  export let show: boolean = false
  export let zindex: number = 2000

  subscribe(modalStore, showModal, `${id}.show`)
  subscribe(modalStore, hideModal, `${id}.hide`)
  subscribe(modalStore, hideModal, `hide`)

  function showModal () {
    const modal = modalStore.get()
    document.body.style.overflow = 'hidden'
    show = true
    zindex = modal.zindex

    onShow(modal.options)
  }

  function hideModal () {
    const modal = modalStore.get()

    // Add the scroll bars back in for the body
    document.body.style.overflow = 'auto'
    show = false
    zindex = modal.zindex

    // Remove all alerts
    alertStore.clear()
    onHide(modal.options)
    
  }

</script>

{#if show}
  <div id={id} class="modal" style="zindex:{zindex};" transition:fade tabIndex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">{title}</h5>
          <button type="button" on:click={hideModal} class="btn-close" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <slot></slot>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal {
    display: block;
  }

  .modal-header {
    padding: 1rem 2rem;
  }

  .modal-footer {
    padding: .75rem;
  }
</style>
